### ISSUE TITLE
docker hub?

### ISSUE THREAD

**Issue by 3dcandy** [ravenium/fragconsole#1]
Any chance of a dockerhub version (cos I am new to containers etc.)

**Comment by ravenium** [comment]
You're in luck - the docker-compose file should take care of all of this for you.  I probably need to update the documentation a bit since I've gotten a bit better with docker myself over the years.  

Once you've made your local config.toml file for srtrelay, you should be able to just do `docker-compose up`

Here's a quick walkthrough (comments added #):

services:
  # this is your voc/srtrelay image - I made a quick container and pushed it to dockerhub.
  srtrelay:
    image: "ravenium/srtrelay:latest"
    ports:
    # this maps 1935:1935 udp to the host, since that's what we'll be using for the SRT protocol.
    # note that SRT doesn't technically have a "traditional" port like RTMP does, it just needs *an* assigned UDP port
      - "1935:1935/udp"
    # this is a docker "private" network that the containers share for communication
    networks:
        - fragforce
    # I'm mapping config.toml so the srtrelay container can use it.  Make sure it exists in the same dir as docker-compose.yaml
    # Grab a copy from voc/srtrelay and follow his instructions.  Change the port to match - it's 1337 in his example
    volumes:
        - $PWD/config.toml:/conf/config.toml
   # This is the "stream preview" container.
  frag_restream_record:
    image: "ravenium/fragconsole:latest"
    # open port 3000 so you can browse to it from your host
    ports:
        - "3000:3000"
     # This command starts the app to do the following:
     #  send all streams it sees to the web console (-s)
     # poll the srtrelay api at our other container's address.  Notice 8080 isn't exposed outside of our docker formation?
     # grab the streams from the other container's stream url
     # listen on port 3000 (matches the ports above) so you can browse to it from your host. 
    command: -s -serverurl http://srtrelay:8080/streams -streamurl srt://srtrelay:1935 -listen 0.0.0.0:3000
    networks:
        - fragforce
    # maps a local folder called record to /record on the host.  If you're not using -r you can comment this out.
    volumes:
        - $PWD/record:/record
networks:
  fragforce:

**Comment by 3dcandy** [comment]
So, thanks. Mucho appreciated. So am I right in saying that I grab the config.toml file, edit it for my own purposes and make sure the port is set to 1935 as my server is at home, and then carry on?

Cheers

**Comment by 3dcandy** [comment]
I still cannot get this to work. I know I'm doing something really silly.... I just get errors running the docker commands

**Comment by ravenium** [comment]
I'd definitely try first with a few sample compose files just to get the basic syntax down.  If you've got a more specific error I can try to spot what's going wrong, too.

**Comment by 3dcandy** [comment]
Yeah it's not an issue I'd just like to get my head around it. I have a docker hub account and I think what I shall do is to get a github account, edit the changes I need for my particular needs and then upload the resulting files to docker hub and use them like that. For me a 200ms latency is far too low, I have edited it to 2000ms and this results in much better results. I have a livestream coming up on October 30th and for then I want the srtrelay and fragconsole combo up and running so I can record the srt feeds to me clean before I add overlays etc. In my quick tests a 2000ms latency with a 50000 buffersize offers a really good mix of latency versus quality and recovery if frames are dropped (it's a music livestream and dropped frames resulting in audio dropouts isn't good)
